"""add cascade delete for users

Revision ID: 77ad2c2290aa
Revises: b7448cd719db
Create Date: 2026-10-03 19:31:25.651252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77ad2c2290aa'
down_revision: Union[str, Sequence[str], None] = 'b7448cd719db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('carts_user_id_fkey'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('products', 'image')
    op.drop_constraint(op.f('review_user_id_fkey'), 'review', type_='foreignkey')
    op.create_foreign_key(None, 'review', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'review', type_='foreignkey')
    op.create_foreign_key(op.f('review_user_id_fkey'), 'review', 'users', ['user_id'], ['id'])
    op.add_column('products', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(op.f('carts_user_id_fkey'), 'carts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
