"""empty message

Revision ID: cbf70f815cb4
Revises: 0e620c19ad96
Create Date: 2026-09-28 17:49:29.511887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbf70f815cb4'
down_revision: Union[str, Sequence[str], None] = '0e620c19ad96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('subcategories_category_id_fkey'), 'subcategories', type_='foreignkey')
    op.create_foreign_key(None, 'subcategories', 'categories', ['category_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subcategories', type_='foreignkey')
    op.create_foreign_key(op.f('subcategories_category_id_fkey'), 'subcategories', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
